### ISSUE TITLE
final test for demo

### ISSUE THREAD

**Issue by namvhoang02** [namvhoang02/aptos-e2e-dapp#31]
## Networks

- [x] Case 1: Switch network to mainnet from devnet (testnet)  
      **Expected**: Display an error screen indicating that mainnet is not supported.
- [x] Case 2: On mainnet, click the button to switch to testnet  
      **Expected**: For wallets that support switching, we should be able to click "switch".  
      For wallets that do not support switching, an error should be displayed suggesting to choose a different wallet.

**Comment by namvhoang02** [comment]
## Tasks

- [ ] Case 1: When accessing an account without a created list, display the "Create List" button.
      **Expected**: aa
- [ ] Case 2: When no list is created, click the "New" button.
      **Expected**: bb
- [ ] Case 3: When a list is created, display the "Create Task" button.
      **Expected**: cc
- [ ] Case 4: dd
      **Expected**: ee
